title: Niel de Kock
logo: 
description: >Data driven teacher exploring the world of data
 
  <a href="https://www.linkedin.com/in/niel-de-kock/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
